<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SiswaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // [
            //     'id_siswa'      => 1,
            //     'nama'          => 'Maulita',
            //     'alamat'        => 'Alamat Maulita',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567001',
            //     'email'         => 'maulita@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'maulita.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 3
            // ],
            // [
            //     'id_siswa'      => 2,
            //     'nama'          => 'Yusri',
            //     'alamat'        => 'Alamat Yusri',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567002',
            //     'email'         => 'yusri@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'yusri.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 4
            // ],
            // [
            //     'id_siswa'      => 3,
            //     'nama'          => 'Kadafi',
            //     'alamat'        => 'Alamat Kadafi',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567003',
            //     'email'         => 'kadafi@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'kadafi.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 5
            // ],
            // [
            //     'id_siswa'      => 4,
            //     'nama'          => 'Putri',
            //     'alamat'        => 'Alamat Putri',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567004',
            //     'email'         => 'putri@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'putri.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 6
            // ],
            // [
            //     'id_siswa'      => 5,
            //     'nama'          => 'Ardian',
            //     'alamat'        => 'Alamat Ardian',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567005',
            //     'email'         => 'ardian@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'ardian.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 7
            // ],
            // [
            //     'id_siswa'      => 6,
            //     'nama'          => 'Adam',
            //     'alamat'        => 'Alamat Adam',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567006',
            //     'email'         => 'adam@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'adam.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 8
            // ],
            // [
            //     'id_siswa'      => 7,
            //     'nama'          => 'Regita',
            //     'alamat'        => 'Alamat Regita',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567007',
            //     'email'         => 'regita@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'regita.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 9
            // ],
            // [
            //     'id_siswa'      => 8,
            //     'nama'          => 'Abdul',
            //     'alamat'        => 'Alamat Abdul',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567008',
            //     'email'         => 'abdul@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'abdul.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 10
            // ],
            // [
            //     'id_siswa'      => 9,
            //     'nama'          => 'Gabriel',
            //     'alamat'        => 'Alamat Gabriel',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567009',
            //     'email'         => 'gabriel@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'gabriel.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 11
            // ],
            // [
            //     'id_siswa'      => 10,
            //     'nama'          => 'Asti',
            //     'alamat'        => 'Alamat Asti',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567010',
            //     'email'         => 'asti@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'asti.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 12
            // ],
            // [
            //     'id_siswa'      => 11,
            //     'nama'          => 'Lukman',
            //     'alamat'        => 'Alamat Lukman',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567011',
            //     'email'         => 'lukman@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'lukman.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 13
            // ],
            // [
            //     'id_siswa'      => 12,
            //     'nama'          => 'Maulana',
            //     'alamat'        => 'Alamat Maulana',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567012',
            //     'email'         => 'maulana@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'maulana.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 14
            // ],
            // [
            //     'id_siswa'      => 13,
            //     'nama'          => 'Icha',
            //     'alamat'        => 'Alamat Icha',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567013',
            //     'email'         => 'icha@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'icha.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 15
            // ],
            // [
            //     'id_siswa'      => 14,
            //     'nama'          => 'Yogi',
            //     'alamat'        => 'Alamat Yogi',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567014',
            //     'email'         => 'yogi@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'yogi.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 16
            // ],
            // [
            //     'id_siswa'      => 15,
            //     'nama'          => 'Febri',
            //     'alamat'        => 'Alamat Febri',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567015',
            //     'email'         => 'febri@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'febri.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 17
            // ],
            // [
            //     'id_siswa'      => 16,
            //     'nama'          => 'Aulia',
            //     'alamat'        => 'Alamat Aulia',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567016',
            //     'email'         => 'aulia@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'aulia.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 18
            // ],
            // [
            //     'id_siswa'      => 17,
            //     'nama'          => 'Wildan',
            //     'alamat'        => 'Alamat Wildan',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567017',
            //     'email'         => 'wildan@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'wildan.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 19
            // ],
            // [
            //     'id_siswa'      => 18,
            //     'nama'          => 'Tia',
            //     'alamat'        => 'Alamat Tia',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567018',
            //     'email'         => 'tia@student.com',
            //     'jenis_kelamin' => 'p',
            //     'foto'          => 'tia.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 20
            // ],
            // [
            //     'id_siswa'      => 19,
            //     'nama'          => 'Ale',
            //     'alamat'        => 'Alamat Ale',
            //     'jurusan'       => 'D4 TI',
            //     'asal_instansi' => 'Politeknik Negeri Malang',
            //     'no_telepon'    => '081234567019',
            //     'email'         => 'ale@student.com',
            //     'jenis_kelamin' => 'l',
            //     'foto'          => 'ale.jpg',
            //     'tgl_masuk'     => date('Y-m-d'),
            //     'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
            //     'status'        => 'Aktif',
            //     'keterangan'    => 'Siswa magang',
            //     'id_user'       => 21
            // ],
            [
                'id_siswa'      => 20,
                'nama'          => 'Nizhar',
                'alamat'        => 'Alamat Nizhar',
                'jurusan'       => 'D4 TI',
                'asal_instansi' => 'Politeknik Negeri Malang',
                'no_telepon'    => '081234567019',
                'email'         => 'ale@student.com',
                'jenis_kelamin' => 'l',
                'foto'          => 'ale.jpg',
                'tgl_masuk'     => date('Y-m-d'),
                'tgl_keluar'    => date('Y-m-d', strtotime('+90 days')),
                'status'        => 'Aktif',
                'keterangan'    => 'Siswa magang',
                'id_user'       => 22
            ],
        ];

        $this->db->table('tb_siswa')->insertBatch($data);
    }
}
